// generator.js
const fs = require("fs");
const path = require("path");

const OUT = path.join(process.cwd(), "posts");
if (!fs.existsSync(OUT)) fs.mkdirSync(OUT);

const titles = [
  "The Power of Pause",
  "Rethinking Rest",
  "The Art of Slowing Down",
  "When Silence Speaks",
  "Stop to Move Forward",
  "The Stillness Strategy",
  "Why Rest Matters More Than Ever",
  "The Pause That Transforms",
  "Hustle Less, Live More",
  "The Hidden Strength of Doing Nothing",
  "Reclaiming Your Energy",
  "Burnout Isn't a Badge",
  "The Calm Reset",
  "Slow Is a Superpower",
  "Unlearning Hustle Culture",
  "The Rest Revolution",
  "Recharge Before You Collapse",
  "The Quiet Choice",
  "Choosing Yourself First",
  "Softness as Strength",
  "The Myth of Constant Motion",
  "Stillness Is Not Laziness",
  "Reset, Restart, Renew",
  "You Don’t Have to Earn Rest",
  "Your Body Knows Before You Do",
  "Pause to Feel Alive",
  "The Rest You’ve Been Avoiding",
  "Stop Ignoring the Signals",
  "Slowness Is Sacred",
  "Let the World Wait",
  "Rest Without Apology",
  "Why You’re Always Tired",
  "Slowing Down to Speed Up",
  "When Exhaustion Becomes Normal",
  "Your Nervous System Is Talking",
  "Pause: A Radical Act",
  "The World Won’t End If You Rest",
  "Break Before You Break",
  "Listen to the Quiet",
  "Doing Less on Purpose",
  "Resting Is Productive",
  "Breathe Before You Burn",
  "Your Future Self Needs Rest",
  "Stop Running From Yourself",
  "The Pause Principle",
  "The Beauty of Doing Nothing",
  "Unplug to Come Back Stronger",
  "Stillness Is a Strategy",
  "Silence as Self-Care"
];

function randomDate() {
  const start = new Date(2023, 0, 1).getTime();
  const end = new Date(2025, 11, 31).getTime();
  const ts = start + Math.random() * (end - start);
  const d = new Date(ts);

  return d.toISOString().split("T")[0];
}

titles.slice(0, 50).forEach((title, i) => {
  const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");
  const date = randomDate();

  const content = `---
title: "${title}"
description: "A mock autogenerated post about rest, pause, and awareness."
image: "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?w=1200"
category: "mindfulness"
readTime: "6 min"
date: "${date}"
---

Your post content goes here. This is a placeholder for **${title}**.`;

  fs.writeFileSync(path.join(OUT, `${date}--${slug}.md`), content);
});

console.log("✓ 50 markdown posts created in /posts");
